name: Build
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '5.6'
          - '7.0'
          - '7.4'
        phpunit-version: ['5']
        include:
          - php-version: '8.2'
            phpunit-version: '8'
    name: PHP ${{ matrix.php-version }} sample
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpunit:${{ matrix.phpunit-version }}
      - env:
          DETECTLANGUAGE_API_KEY: ${{ secrets.DETECTLANGUAGE_API_KEY }}
        run: phpunit
