name: Release to Packagist
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch packagist update
        run: |
          curl -X POST -d '{"repository":{"url":"https://github.com/detectlanguage/detectlanguage-php"}}' \
            -H "Content-Type: application/json" \
            https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}
